#!/bin/sh
# check - Runs shellcheck on git scripts (and other shell scripts).
#
# This file is part of gitscripts, some custom git commands.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

status=0

for f in check deploy git-*; do
    printf 'Checking %s.\n' "$f"
    shellcheck "$f" || status="$?"
done

exit "$status"
