#!/bin/sh
# git-pull-all - check out and pull from all remote branches

set -f

filter_remote_branches() {
    sed -nE 's|^[[:space:]]*remotes/origin/([^[:space:]]+)$|\1|p'
}

status=0

quit() {
    exit "$status"
}

err() {
    format="$1"
    shift
    printf "%s: $format\\n" "$0" "$@"
    status=1
}

if ! current="$(git symbolic-ref --short HEAD)"; then
    err "can't find current branch"
    quit
fi

for b in $(git branch -a | filter_remote_branches); do
    { git checkout "$b" && git pull; } || err "can't update %s" "$b"
done

git checkout "$current" || err "can't return to %s" "$current"
quit
