#!/usr/bin/env perl
# git-lsx - Lists files in the index, emphasizing those marked executable.
#
# This file is part of gitscripts, some custom git commands.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

use strict;
use warnings;

open(my $f, 'git ls-files -s |');

while (<$f>) {

}
